"""Initial migration

Revision ID: 2a885a0fa82e
Revises: 
Create Date: 2024-01-17 01:55:01.268863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a885a0fa82e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_rule',
    sa.Column('rule_id', sa.String(length=3), nullable=False),
    sa.Column('cibil_lower', sa.Float(), nullable=True),
    sa.Column('cibil_higher', sa.Float(), nullable=True),
    sa.Column('loan_amount_lower', sa.Float(), nullable=True),
    sa.Column('loan_amount_higher', sa.Float(), nullable=True),
    sa.Column('loan_period_lower', sa.Float(), nullable=True),
    sa.Column('loan_period_higher', sa.Float(), nullable=True),
    sa.Column('loan_interest', sa.Float(), nullable=True),
    sa.Column('loan_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_rule')
    # ### end Alembic commands ###
